package ru.funfake.funfakeonline.generators;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class NameGenerator {

    private static final List<String> decorator = new ArrayList<>();
    private static final List<String> start = new ArrayList<>();
    private static final List<String> finish = new ArrayList<>();
    private static final List<String> singular = new ArrayList<>();

    public NameGenerator() {
        decorator.add("xX");
        decorator.add("Mr");
        decorator.add("_");
        decorator.add("z");
        decorator.add("zZ");
        decorator.add("u");
        decorator.add("1");
        decorator.add("The");
        decorator.add("An");
        decorator.add("A");
        decorator.add("a");
        decorator.add("da");
        start.add("Sleepy");
        start.add("Dark");
        start.add("Sneaky");
        start.add("Awesome");
        start.add("Cool");
        start.add("Fast");
        start.add("Pro");
        start.add("Tiny");
        start.add("Lil");
        start.add("Funny");
        start.add("Elite");
        start.add("Accurate");
        start.add("Fast");
        start.add("Super");
        start.add("Dazzling");
        start.add("Purple");
        start.add("Red");
        start.add("Blue");
        start.add("Yellow");
        start.add("Jumpy");
        start.add("Cute");
        start.add("Ugly");
        start.add("Diamond");
        start.add("Golden");
        start.add("Fried");
        start.add("Powerful");
        start.add("Greasy");
        start.add("Oily");
        start.add("Ultimate");
        start.add("Arab");
        start.add("Timid");
        start.add("Spooky");
        start.add("Creepy");
        start.add("Juicy");
        start.add("Grimacing");
        start.add("Grim");
        start.add("German");
        start.add("Iron");
        start.add("Obsidian");
        start.add("Bedrock");
        start.add("Toxic");
        start.add("Little");
        start.add("Prof");
        start.add("Professor");
        start.add("Janky");
        start.add("Greek");
        start.add("Crazy");
        start.add("Extinct");
        start.add("Frozen");
        start.add("Flaming");
        start.add("Evil");
        start.add("Happy");
        start.add("Fruity");
        start.add("Ultra");
        start.add("Legendary");
        start.add("Platinum");
        start.add("Bossy");
        start.add("Rude");
        start.add("Flightless");
        start.add("Freezing");
        start.add("Frosty");
        start.add("Camping");
        start.add("Genetic");
        start.add("Generic");
        start.add("Mining");
        start.add("Deutsche");
        start.add("Logic");
        start.add("Wandering");
        start.add("Racing");
        start.add("Raving");
        finish.add("Dude");
        finish.add("Champion");
        finish.add("Legend");
        finish.add("Gamer");
        finish.add("Assassin");
        finish.add("Player");
        finish.add("Master");
        finish.add("Daredevil");
        finish.add("Blade");
        finish.add("Boot");
        finish.add("Guy");
        finish.add("Governor");
        finish.add("Passenger");
        finish.add("Man");
        finish.add("Lord");
        finish.add("Turtle");
        finish.add("Chicken");
        finish.add("Destroyer");
        finish.add("Grandpa");
        finish.add("Grandma");
        finish.add("Pilot");
        finish.add("Reaper");
        finish.add("Farmer");
        finish.add("Fish");
        finish.add("Zebra");
        finish.add("Giraffe");
        finish.add("Golem");
        finish.add("Creeper");
        finish.add("Enderman");
        finish.add("Demon");
        finish.add("Devil");
        finish.add("God");
        finish.add("Sand");
        finish.add("Wither");
        finish.add("Dragon");
        finish.add("Cow");
        finish.add("Sheep");
        finish.add("Dog");
        finish.add("Wolf");
        finish.add("Girl");
        finish.add("Panda");
        finish.add("Husky");
        finish.add("Shark");
        finish.add("Lizard");
        finish.add("Snake");
        finish.add("Venom");
        finish.add("Baby");
        finish.add("Forest");
        finish.add("Crafter");
        finish.add("Ravanger");
        finish.add("Trader");
        finish.add("Fisher");
        finish.add("Monster");
        singular.add("Crubeen");
        singular.add("Anomalous");
        singular.add("Zephyr");
        singular.add("Zephyrus");
        singular.add("Scootch");
        singular.add("Ruddock");
        singular.add("HalimWhoop");
        singular.add("Arbalest");
        singular.add("Thuggee");
        singular.add("Hormone");
        singular.add("Bumicky");
        singular.add("Blackguard");
        singular.add("ZachaClevis");
        singular.add("NordCraft");
        singular.add("Debouch");
        singular.add("Flabbergast");
        singular.add("Arrhizal");
        singular.add("Parapet");
        singular.add("Zubrowka");
        singular.add("Gymkhana");
        singular.add("Eclosion");
        singular.add("MoriaAloof");
        singular.add("Cupuliferous");
        singular.add("Sollevation");
        singular.add("Celation");
        singular.add("Serotinous");
        singular.add("Bodacious");
        singular.add("ThemeisGlom");
        singular.add("Sacristy");
        singular.add("Earwig");
        singular.add("Geta");
        singular.add("Jetsam");
        singular.add("Contraband");
        singular.add("Nipperkin");
        singular.add("Crotchet");
        singular.add("Subtopia");
        singular.add("Intinction");
        singular.add("Platapie");
        singular.add("Glozing");
        singular.add("LunicSpew");
        singular.add("Notabilia");
        singular.add("Puncheon");
        singular.add("Rhubarb");
        singular.add("Trapezoid");
        singular.add("Pannage");
        singular.add("Mudslinger");
        singular.add("Blob");
        singular.add("Yaws");
        singular.add("Quicksilver");
        singular.add("Wispywas");
        singular.add("Monorchid");
        singular.add("Agamogenesis");
        singular.add("Iceland");
        singular.add("Piquant");
        singular.add("Pleiomorphy");
        singular.add("Amyloid");
        singular.add("Jalopy");
        singular.add("Epulotic");
        singular.add("Scrotiform");
        singular.add("Integrity");
        singular.add("Whippy");
        singular.add("Uvula");
        singular.add("Drysalter");
        singular.add("Miffed");
        singular.add("Nepotation");
        singular.add("Bibliopole");
        singular.add("Sphragistics");
        singular.add("Fuliguline");
        singular.add("Logicism");
        singular.add("Frondeur");
        singular.add("Troika");
        singular.add("Catamaran");
        singular.add("Caesious");
        singular.add("Beestings");
        singular.add("Didgeridoo");
        singular.add("Hydromancy");
        singular.add("Boysim");
        singular.add("Bossyshark");
        singular.add("Billyben");
        singular.add("Wolfdoll");
    }

    public String generateName() {
        String name = "";
        if (new Random().nextInt(100) >= 75) {
            name = name + decorator.get((new Random()).nextInt(decorator.size()));
        }

        if (new Random().nextInt(10) >= 7) {
            name = name + start.get((new Random()).nextInt(start.size()));
            name = name + finish.get((new Random()).nextInt(finish.size()));
        } else {
            name = name + singular.get((new Random()).nextInt(singular.size()));
        }

        if (new Random().nextInt(5) <= 2 && name.length() <= 13) {
            name = name + new Random().nextInt(99);
        }
        if (name.length() > 16) name = name.substring(0, 16);
        return name;
    }
}
